# -*- coding: utf-8 -*-
"""ALFRED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JEjkQxFWcr_ovuxi5fbT81D7ArOwwq_7
"""

#pip install pyttsx3
import pyttsx3

#pip install SpeechRecognition

import webbrowser #web browsing module

import speech_recognition as sr #Speech recognintion module

import datetime #To aske time and date module

#pip install pyjokes #port pyjokes

import pyttsx3 #Python text to speech conversion module

#pip install --upgrade pip



#apt-get install -y python-dev portaudio19-dev

#sudo pip install --no-cache-dir pyaudio

#pip install virtualenv

#virtualenv myenv

#source myenv/bin/activate

#pip install package_name

#whoami

def sptext(): #it will take input from us but will not return anything 

  recognizer = sr.Recognizer() #sr is module name and Recognizer is class name, it is used to store voice in recognizer variable 

  with sr.Microphone() as source: #inut through microphone as source 

    print("You can talk now, I am Listening...") #It will print while you are talking/commanding/requesting

    recognizer.adjust_for_ambient_noise(source)#noise cancellation i.e. the syntax to remove noise from source

    audio = recognizer.listen(source) #listen from source, it will be stored in audio variable

    try:  #to avoid error displaying we are going to use try catch as if voice is not recognized then it will avoid error and throw exception 
      print("Recognizing...")   #display during recognition process

      data = recognizer.recognize_google(audio)   #recognizer function of google sourced from audio 

      print(data)                  #it will print what it recognized using speech recognizer module which we imported 

    except sr.UnknownValueError:
      print("Sorry! I did not understand what you said. ")


sptext()